### ISSUE TITLE
感觉很好用。

### ISSUE THREAD

**Issue by hebw** [Geocld/web-wechat-chrome-extension#1]
非常感谢，感觉很好用。
我想尝试做一个smartqq的插件，可以使用你的代码吗？

**Comment by Geocld** [comment]
@hebw 只能参照思路做，smartqq没有用到angular作为前端框架，在获取聊天列表和好友时需要使用纯dom方式获取

**Comment by hebw** [comment]
> @hebw 只能参照思路做，smartqq没有用到angular作为前端框架，在获取聊天列表和好友时需要使用纯dom方式获取

好呢
